In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [3]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range('20130101', periods=6)

In [5]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [7]:
df

                   A         B         C         D
2013-01-01  1.606217  0.855340  0.511767  0.692767
2013-01-02 -0.804893  0.612661 -1.261758 -0.128382
2013-01-03 -0.217233 -0.598846  0.008532  0.576786
2013-01-04 -0.661728  0.887145 -0.124807  1.468001
2013-01-05  0.642605  0.593016  1.015690  1.641959
2013-01-06 -0.888369 -1.403047 -1.007927 -0.348572

In [8]:
df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'foo'})
   ...:

In [9]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [10]:
df2.B

0   2013-01-02
1   2013-01-02
2   2013-01-02
3   2013-01-02
Name: B, dtype: datetime64[ns]

In [11]:
df2.describe()

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [12]:
df = pd.read_csv("../dataset/prova.csv")

In [13]:
df

,screen_name,date,text,retweet_count,favourites_count
0,Orietta's Recipes,2020-01-17 18:09:56,Stasera cena a base di pesce! Tonno alla piast...,15,49
1,Orietta's Recipes,2020-01-17 11:57:39,"Buon pranzo, io oggi pranzo leggero con il mio...",23,67
2,Orietta's Recipes,2020-01-17 07:51:15,Buongiorno e grazie ancora a tutti per gli aug...,16,85
3,Orietta's Recipes,2020-01-16 17:28:59,Biscotti delicati di sabbia 😋 ❤️😘🥂🥂🍾.! https:/...,25,166
4,Orietta's Recipes,2020-01-16 13:51:03,Oggi è il mio compleanno 🎂 🥂 ❤️ amici! Vorrei ...,45,482
5,Orietta's Recipes,2020-01-16 11:46:01,Io oggi riso integrale con crema di piselli 😋 ...,14,68
6,Orietta's Recipes,2020-01-16 07:36:10,Oggi ho proprio voglia di qualcosa di buono do...,26,117
7,Orietta's Recipes,2020-01-15 18:24:25,"Buona cena amici, io stasera polpette di halib...",25,104
8,Orietta's Recipes,2020-01-15 11:39:56,Oggi ho proprio voglia di un piatto di trofie ...,17,62
9,Orietta's Recipes,2020-01-15 07:38:50,Buongiorno! 😁😘 oggi condivido con voi la mia 😀...,48,171
10,Orietta's Recipes,2020-01-14 17:59:22,"Stasera per cena, involtini di cavolo cinese c...",21,102
11,Orietta's Recipes,2020-01-14 11:52:32,"Oggi pasta con zucchine e primo sale, semplice...",19,74
12,Orietta's Recipes,2020-01-14 07:53:59,Buongiorno amici 🤗😘🤗😘❤️Chi vuole per colazione...,21,127
13,Orietta's Recipes,2020-01-13 18:15:28,Stasera come contorno mini carote speziate al ...,12,59
14,Orietta's Recipes,2020-01-13 11:43:54,Spaghetti con polpo e 'nduja 😋 😋 se non li ave...,27,102
15,Orietta's Recipes,2020-01-13 07:54:36,"Buon inizio settimana a tutti voi,☺️ oggi per ...",27,106
16,Orietta's Recipes,2020-01-12 18:10:18,La mia cena informale ☺️ con pane semi integra...,15,78
17,Orietta's Recipes,2020-01-12 11:38:09,"Buon pranzo domenicale amici ☺️, spero siate i...",15,94
18,Orietta's Recipes,2020-01-12 08:07:22,Buongiorno e buona domenica 💕Sto preparando le...,20,111
19,Orietta's Recipes,2020-01-11 18:53:19,Buona Pizza a tutti ☺️ ☺️ 😀 🍕🍻 🍕 🍕 #SaturdayM...,30,179
20,Orietta's Recipes,2020-01-11 11:30:51,Oggi penne all'arrabbiata! 😋 🍷. Con un primo c...,24,116
21,Orietta's Recipes,2020-01-11 07:57:43,Ben svegliati 💕! Stamattina la mia colazione ...,17,83
22,Orietta's Recipes,2020-01-10 17:55:43,Non sapete cosa preparare per cena? Vi do un'i...,14,78
23,Orietta's Recipes,2020-01-10 14:05:22,Esco a fare due passi e mi rilasso un po' ☕☕ 😘...,13,125
24,Orietta's Recipes,2020-01-10 11:28:53,"Oggi rigatoni con trota salmonata, bottarga di...",19,60
25,Orietta's Recipes,2020-01-10 07:03:27,Buongiorno! Oggi iniziamo la giornata 💕 con ...,41,152
26,Orietta's Recipes,2020-01-09 18:18:16,Stasera per cena propongo 😋 Soufflé di carote ...,18,83

In [15]:
df['text']

KeyError: 'text'